[Docs/Building.md] Added some Arch Linux specific build instructions, no change to cppcheck as I haven't tested it yet.
etternagame/etterna pull request #961
Opened 2021-03-16 00:10 UTC by DirtyCasting

Spent a few minutes trying to compile, ran into an issue with CMake not finding my openssl install.  This just adds the command to install dependencies, ninja, and a one-line change under configuration for a quick fix to the issue.

2021-03-16 00:20 UTC, poco0317 requested changes
The base of the PR should be the develop branch. It is worth testing to see if building works without these extra instructions on a very recent checkout of develop as well, since we changed the openssl cmake just a little.

2021-03-16 00:20 UTC, poco0317 commented on Docs/Building.md
> +- > **Note for Arch Linux Users:** CMake has trouble finding `libssl` and `libcrypto` by defeault.  Specifying them with `-DOPENSSL_SSL_LIBRARY=/usr/lib/libssl.so.1.1` and `-DOPENSSL_CRYPTO_LIBRARY=/
`defeault` -> `default`

2021-03-16 00:20 UTC, poco0317 commented on Docs/Building.md
> +- > **Note for Arch Linux Users:** CMake has trouble finding `libssl` and `libcrypto` by defeault.  Specifying them with `-DOPENSSL_SSL_LIBRARY=/usr/lib/libssl.so.1.1` and `-DOPENSSL_CRYPTO_LIBRARY=/
Also consider rewording and/or instead using full code blocks to try to get these commands to not be split across lines.

2021-05-03 21:57 UTC, jameskr97 commented
Huh, Déjà vu. Try develop. Arch should work on develop without anything extra *I think*.

2021-05-04 04:06 UTC, Ulti-FD commented
Haven't had any issues as of recent on develop

2021-05-04 18:52 UTC, jameskr97 commented
> Haven't had any issues as of recent on develop

Yeah, I've been away from the project for a little while, but I definitely remember coming across this and fixing it.

2021-06-26 22:38 UTC, poco0317 commented
superceded by current develop changes and the existence of the AUR package `etterna`

reopen if issue is present on latest develop branch and the requested changes are made

2021-06-26 22:38 UTC, closed without merging